app/models/user.py
from app.extensions import db
from app.models.base import Base

class User(Base):
  __tablename__ = "Users"
 
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  username = db.Column(db.String())
  password = db.Column(db.String())

  def __init__(self, username:str, password:str):
    self.username = username
    self.password = password
  
  # def __repr__(self):
  #     return f"{self.first_name} {self.last_name} : {self.id} : {self.date_created}"

app/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from app.users import routes

app/users/routes.py
from flask import render_template, url_for, redirect
from app.users import bp
from faker import Faker


fake = Faker()
data = [
  {
    "name" : "Sergio Rodrigo Cardenas Rivera",
    "user_name": "sergio.cardenas",
    "last_connection": "2023-03-29",
  },
  {
    "name" : "Miriam Lucana",
    "user_name": "miriam.lucana",
    "last_connection": "2023-03-29",
  },
  {
    "name" : "Pedro Peredo",
    "user_name": "pedro.peredo",
    "last_connection": "2023-03-29",
  },
  {
    "name" : "Jorge Javier",
    "user_name": "jorge.javier",
    "last_connection": "2023-03-29",
  },
]

@bp.route('/')
def index():
  return render_template('users/index.html', data=data)
  # else:
  #   return redirect(url_for('main.show_the_login_form'))
@bp.route('/add_user')
def method():
  new_data = {
    "name" : fake.name(),
    "user_name": fake.address(),
    "last_connection": "2023-03-29",
  }
  data.append(new_data)
  # return redirect(url_for('.index'))
  # return render_template('users/index.html', data=data)
  return new_data
  

app/templates/users/index.html
{% extends 'base.html' %}
{% block content %}
<div>
  <!-- <h2 class="text-2xl"> Usuarios </h2> -->
  <div class="flex-column">
    <!-- <h1 class="text-center">Center aligned text on all viewport sizes.</h1> -->
    <div class="d-flex justify-content-center m-5  pl-10 pr-10">  
      <div class="flex justify-center pb-5 pt-5">
        <a href="#ex1" rel="modal:open">
          <button type="button" class="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center me-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 me-2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M18 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0ZM3 19.235v-.11a6.375 6.375 0 0 1 12.75 0v.109A12.318 12.318 0 0 1 9.374 21c-2.331 0-4.512-.645-6.374-1.766Z" />
            </svg>
            Nuevo Usuario
          </button>
        </a>
        <button type="button" class="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center me-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800" onclick="addfakeuser()">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 me-2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M18 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0ZM3 19.235v-.11a6.375 6.375 0 0 1 12.75 0v.109A12.318 12.318 0 0 1 9.374 21c-2.331 0-4.512-.645-6.374-1.766Z" />
          </svg>
          New Fake User
        </button>
      </div>
      <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <table id="usersTable" class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
            <thead class="flex w-full text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr class="flex w-full mb-4">
                  <th scope="col" class="px-6 py-3">
                    Nombre Completo
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Nombre de Usuario
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Ultima conexión
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Estado
                  </th>
                </tr>
            </thead>
            <tbody id="usersTableBody" class="bg-grey-light flex flex-col items-center justify-between overflow-y-scroll w-full" style="height: 50vh;">
              {% for item in data %}
                <tr class="flex w-full mb-4 odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
                  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    {{item['name']}}
                  </th>
                  <td class="px-6 py-4">
                    {{item['user_name']}}
                  </td>
                  <td class="px-6 py-4">
                    {{item['last_connection']}}
                  </td>
                  <td class="px-6 py-4">
                      <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                  </td>
                </tr> 
              {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div id="ex1" class="modal">
    <form class="space-y-4 md:space-y-6" action="{{ url_for('users.index')}}" method="post">
      <div class="modal-header mt-3 text-center">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
          Nuevo Usuario
        </h1>
      </div>
      <div class="modal-body">
        <div class="block mb-3">
          <label for="username" class="block mb-1 text-sm font-medium text-gray-900 dark:text-white">Apellido Paterno</label>
          <!-- placeholder="Apellido Paterno" -->
          <input type="text" name="username" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
        </div>

        <div class="block mb-3">
          <label for="username" class="block mb-1 text-sm font-medium text-gray-900 dark:text-white">Apellido Materno</label>
          <input type="text" name="username" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
        </div>

        <div class="block mb-3">
          <label for="username" class="block mb-1 text-sm font-medium text-gray-900 dark:text-white">Primer Nombre</label>
          <input type="text" name="username" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="" required="">
        </div>
        <div class="block mb-3">
          <label for="username" class="block mb-1 text-sm font-medium text-gray-900 dark:text-white">Segundo Nombre</label>
          <input type="text" name="username" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="" required="">
        </div>
        <div class="block mb-3">
          <label for="username" class="block mb-1 text-sm font-medium text-gray-900 dark:text-white">Cédula de identidad</label>
          <input type="text" name="userdata" id="ci" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="" required="">
        </div>
        <div class="flex justify-center pb-2 pt-3">
          <div class="flex items-center me-4">
            <input checked id="inline-radio" type="radio" value="" name="inline-radio-group" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
            <label for="inline-radio" class="ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">Vecino</label>
          </div>
          <div class="flex items-center me-4">
            <input id="inline-2-radio" type="radio" value="" name="inline-radio-group" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
            <label for="inline-2-radio" class="ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">Usuario</label>
          </div>
        </div>
        <div class="border border-gray-200 rounded-lg p-5 mb-3">
          <div class="mb-3">
            <label for="first_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nombre de Usuario</label>
            <input type="text" id="user_name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Nombre para ingresar al sistema" required />
          </div>
          <div>
            <label for="last_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Contraseña</label>
            <input type="password" id="last_name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Password" required />
          </div>
        </div>
        <div class="flex justify-center">
          <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 me-2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M18 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0ZM3 19.235v-.11a6.375 6.375 0 0 1 12.75 0v.109A12.318 12.318 0 0 1 9.374 21c-2.331 0-4.512-.645-6.374-1.766Z" />
            </svg>
            Registrar
          </button>
          <a rel="modal:close">
            <button type="button" class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 inline-flex items-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 me-2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
              </svg>                          
              Cancelar
            </button>
          </a>
          
        </div>
    </form>
  <!-- <a href="#" rel="modal:close">Close</a> -->
</div>
{% block scripts %}
  <script>
    // console.log('esto es un mensaje');
    // $(document).ready(function () {
    //   $('#usersTable').DataTable();
    // });
  </script>
{% endblock %}

{% endblock %}